/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.anomind;

import com.google.common.base.Strings;

import java.util.Random;

public class HelloOtus {
    public static void main(String... args) {
        System.out.println(Strings.repeat("Hello", new Random().nextInt(10)));
    }
}
